import React, { useState } from 'react';
import { ToolHeader } from '../components/ToolHeader';
import { FileJson, Code, AlertTriangle, CheckCircle2, Wand2 } from 'lucide-react';

const SAMPLE_JSON = `{
  "id": "usr_99812",
  "name": "Jane Developer",
  "email": "jane@example.com",
  "roles": ["admin", "developer"],
  "settings": {
    "theme": "dark",
    "notifications": true,
    "loginCount": 42
  },
  "metadata": null
}`;

export const JsonFormatter: React.FC = () => {
  const [jsonInput, setJsonInput] = useState<string>(SAMPLE_JSON);
  const [indentSize, setIndentSize] = useState<number | 'tab' | 'compact'>(2);
  const [targetType, setTargetType] = useState<'none' | 'typescript' | 'go' | 'python'>('none');

  // Format & Validate JSON
  const processJson = () => {
    if (!jsonInput.trim()) return { formatted: '', error: null, isValid: false };

    try {
      const parsed = JSON.parse(jsonInput);

      let formatted = '';
      if (indentSize === 'compact') {
        formatted = JSON.stringify(parsed);
      } else if (indentSize === 'tab') {
        formatted = JSON.stringify(parsed, null, '\t');
      } else {
        formatted = JSON.stringify(parsed, null, indentSize);
      }

      return { formatted, error: null, isValid: true, parsed };
    } catch (err: any) {
      return { formatted: '', error: err.message, isValid: false, parsed: null };
    }
  };

  const { formatted, error, isValid, parsed } = processJson();

  // Smart repair common loose JSON syntax (single quotes, trailing commas)
  const handleAutoRepair = () => {
    let raw = jsonInput;
    // Replace single quotes around keys/values with double quotes
    raw = raw.replace(/'([^'\\]*(\\.[^'\\]*)*)'/g, '"$1"');
    // Remove trailing commas in objects and arrays
    raw = raw.replace(/,\s*([\]}])/g, '$1');
    setJsonInput(raw);
  };

  // Generate TypeScript Interface
  const generateTypescript = (obj: any, interfaceName = 'RootObject'): string => {
    if (obj === null) return 'type RootObject = null;';
    if (typeof obj !== 'object') return `type RootObject = ${typeof obj};`;

    const getType = (val: any): string => {
      if (val === null) return 'null';
      if (Array.isArray(val)) {
        if (val.length === 0) return 'any[]';
        return `${getType(val[0])}[]`;
      }
      if (typeof val === 'object') return 'Record<string, any>';
      return typeof val;
    };

    let result = `export interface ${interfaceName} {\n`;
    for (const [key, val] of Object.entries(obj)) {
      result += `  ${key}: ${getType(val)};\n`;
    }
    result += `}`;
    return result;
  };

  // Generate Go Struct
  const generateGo = (obj: any, structName = 'AutoGenerated'): string => {
    if (typeof obj !== 'object' || obj === null) return 'type AutoGenerated struct{}';

    const getGoType = (val: any): string => {
      if (val === null) return 'interface{}';
      if (typeof val === 'number') return Number.isInteger(val) ? 'int' : 'float64';
      if (typeof val === 'boolean') return 'bool';
      if (typeof val === 'string') return 'string';
      if (Array.isArray(val)) return `[]${val.length ? getGoType(val[0]) : 'interface{}'}`;
      return 'struct{}';
    };

    const capitalize = (str: string) => str.charAt(0).toUpperCase() + str.slice(1);

    let result = `type ${structName} struct {\n`;
    for (const [key, val] of Object.entries(obj)) {
      result += `\t${capitalize(key)} ${getGoType(val)} \`json:"${key}"\`\n`;
    }
    result += `}`;
    return result;
  };

  // Target Code Type Generator Output
  const renderGeneratedType = () => {
    if (!parsed) return '';
    if (targetType === 'typescript') return generateTypescript(parsed);
    if (targetType === 'go') return generateGo(parsed);
    return '';
  };

  return (
    <div className="space-y-6">
      <ToolHeader
        title="JSON Formatter, Beautifier & Validator"
        description="Format, validate, repair JSON payloads and generate TypeScript or Go type interfaces."
        onLoadSample={() => setJsonInput(SAMPLE_JSON)}
        onClear={() => setJsonInput('')}
        onCopy={() => {
          const content = targetType !== 'none' ? renderGeneratedType() : formatted;
          if (content) navigator.clipboard.writeText(content);
        }}
        onDownload={() => {
          if (!formatted) return;
          const blob = new Blob([formatted], { type: 'application/json' });
          const url = URL.createObjectURL(blob);
          const a = document.createElement('a');
          a.href = url;
          a.download = 'formatted.json';
          a.click();
        }}
      />

      {/* Control Toolbar */}
      <div className="flex flex-wrap items-center justify-between gap-4 p-4 rounded-2xl bg-gray-900/80 border border-gray-800">
        <div className="flex items-center gap-3">
          <span className="text-xs text-gray-400 font-medium">Indentation:</span>
          <div className="flex items-center gap-1 bg-gray-950 p-1 rounded-xl border border-gray-800 text-xs">
            <button
              onClick={() => setIndentSize(2)}
              className={`px-2.5 py-1 rounded-lg ${indentSize === 2 ? 'bg-indigo-600 text-white' : 'text-gray-400'}`}
            >
              2 Spaces
            </button>
            <button
              onClick={() => setIndentSize(4)}
              className={`px-2.5 py-1 rounded-lg ${indentSize === 4 ? 'bg-indigo-600 text-white' : 'text-gray-400'}`}
            >
              4 Spaces
            </button>
            <button
              onClick={() => setIndentSize('tab')}
              className={`px-2.5 py-1 rounded-lg ${indentSize === 'tab' ? 'bg-indigo-600 text-white' : 'text-gray-400'}`}
            >
              Tab
            </button>
            <button
              onClick={() => setIndentSize('compact')}
              className={`px-2.5 py-1 rounded-lg ${indentSize === 'compact' ? 'bg-indigo-600 text-white' : 'text-gray-400'}`}
            >
              Minify
            </button>
          </div>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={handleAutoRepair}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium rounded-xl bg-purple-500/10 hover:bg-purple-500/20 text-purple-300 border border-purple-500/30"
          >
            <Wand2 className="w-3.5 h-3.5" /> Auto-Fix Syntax
          </button>

          <select
            value={targetType}
            onChange={(e: any) => setTargetType(e.target.value)}
            className="glass-input px-3 py-1.5 rounded-xl text-xs font-medium text-gray-300"
          >
            <option value="none">Format Output</option>
            <option value="typescript">Generate TypeScript Interface</option>
            <option value="go">Generate Go Struct</option>
          </select>
        </div>
      </div>

      {/* Editor Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Input */}
        <div className="space-y-2">
          <div className="flex items-center justify-between">
            <label className="block text-xs font-semibold text-gray-300">Input JSON</label>
            {error ? (
              <span className="flex items-center gap-1 text-[11px] text-red-400 font-medium">
                <AlertTriangle className="w-3.5 h-3.5" /> Invalid JSON Syntax
              </span>
            ) : isValid ? (
              <span className="flex items-center gap-1 text-[11px] text-emerald-400 font-medium">
                <CheckCircle2 className="w-3.5 h-3.5" /> Valid JSON
              </span>
            ) : null}
          </div>

          <textarea
            rows={18}
            value={jsonInput}
            onChange={(e) => setJsonInput(e.target.value)}
            placeholder="Paste raw or unformatted JSON here..."
            className="w-full glass-input p-4 rounded-2xl text-xs font-mono leading-relaxed"
          />

          {error && (
            <div className="p-3 rounded-xl bg-red-500/10 border border-red-500/20 text-red-400 text-xs font-mono">
              Error details: {error}
            </div>
          )}
        </div>

        {/* Output */}
        <div className="space-y-2">
          <label className="block text-xs font-semibold text-gray-300">
            {targetType === 'none' ? 'Formatted Result' : `${targetType.toUpperCase()} Type Definition`}
          </label>

          <textarea
            rows={18}
            readOnly
            value={targetType !== 'none' ? renderGeneratedType() : formatted}
            placeholder="Formatted output will appear here..."
            className="w-full glass-input p-4 rounded-2xl text-xs font-mono text-emerald-300 leading-relaxed bg-gray-950/90"
          />
        </div>
      </div>
    </div>
  );
};
